Us591672 upload files implementation
CAAPIM/iOS-MAS-Foundation pull request #217
Opened 2019-08-20 10:39 UTC by mahithegeek

2019-08-26 08:08 UTC, ysd24 requested changes

2019-08-26 08:08 UTC, ysd24 commented on MASFoundation/Classes/_private_/services/network/requests/MASPostFormURLRequest.h
> +//  MASFoundation
Update the developer and license header.

2019-08-26 08:08 UTC, ysd24 commented on MASFoundation/Classes/_private_/services/network/requests/MASPostFormURLRequest.m
> +//  MASFoundation
Update the developer and license header.

2019-08-26 08:08 UTC, ysd24 commented on MASFoundation/Classes/models/Network/MASMultiPartFormData.h
> +//  MASFoundation
Update the developer and license header.

2019-08-26 08:08 UTC, ysd24 commented on MASFoundation/Classes/models/Network/MASMultiPartRequestSerializer.h
> +//  MASMultiPartRequestSerializer.h
Update the developer and license header.

2019-08-26 08:08 UTC, ysd24 commented on MASFoundation/Classes/models/Network/MASMultiPartRequestSerializer.m
> +//  MASMultiPartRequestSerializer.m
Update the developer and license header.

2019-08-26 10:18 UTC, mahithegeek commented on MASFoundation/Classes/_private_/services/network/requests/MASPostFormURLRequest.h
> +//  MASFoundation
done

2019-08-26 10:20 UTC, mahithegeek commented on MASFoundation/Classes/models/Network/MASMultiPartFormData.h
> +//  MASFoundation
done

2019-08-27 05:53 UTC, ysd24 approved these changes

2019-08-27 05:53 UTC, merged