[iOS] MAS credentials should be stored in the keychain as device only
CAAPIM/iOS-MAS-Foundation pull request #90
Opened 2017-10-04 22:55 UTC by rodrigoareis

2017-10-05 17:33 UTC, jhoongo requested changes
Please review my comment, and return the ticket back to me.

2017-10-05 17:33 UTC, jhoongo commented on MASFoundation/Classes/_private_/services/access/MASAccessService.m
> +    localStorage.synchronizable = FALSE;
Please avoid using TRUE/FALSE, and use YES/NO.

2017-10-05 17:33 UTC, jhoongo commented on MASFoundation/Classes/_private_/services/access/MASAccessService.m
> +        sharedStorage.synchronizable = FALSE;
Please avoid using TRUE/FALSE, and use YES/NO.

2017-10-05 17:38 UTC, jhoongo submitted a review, later dismissed
looks good to me

2017-10-12 22:41 UTC, lsanches approved these changes
Approved!

2017-10-16 23:39 UTC, merged